<a href="https://colab.research.google.com/github/tasosnikitakis/Machine-and-Deep-Learning/blob/main/Football_Predictions_ANN_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

## Part 1 - Data Preprocessing

### Importing the dataset

The neccesery libraries for ANN is numpy, pandas for data management and handling, tensorflow for the ANN nodes creation and scikit learn for neccesery machine learn functions

In [2]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [3]:
tf.__version__

'2.12.0'

The main dataset is the seria_data_bs.csv, it contains all the independent variables and the dependent football game outcome. The dataset is then split to the x independent variables and the y dependent variable set (H for home win, D for Draw and A for away win). The iloc function is used and it takes all the rows [:] and all the columns except the last one [:-1] for the x set and again all the rows [:] and just the last column [-1] for the y set

In [5]:
dataset = pd.read_csv('seria_data_bs.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[[ 1.44  4.75  7.   ...  1.41  4.75  8.14]
 [ 4.33  3.9   1.75 ...  4.45  3.91  1.77]
 [10.    5.75  1.28 ... 10.22  5.67  1.3 ]
 ...
 [ 4.33  3.6   1.75 ...  4.89  3.54  1.79]
 [ 2.75  3.    2.75 ...  2.82  3.04  2.76]
 [ 1.91  3.4   4.   ...  1.98  3.45  4.01]]


In [6]:
print(y)

['H' 'A' 'A' 'A' 'H' 'H' 'A' 'H' 'A' 'H' 'D' 'D' 'H' 'H' 'D' 'H' 'D' 'D'
 'H' 'D' 'A' 'H' 'A' 'D' 'H' 'D' 'H' 'A' 'D' 'D' 'D' 'H' 'H' 'D' 'D' 'H'
 'H' 'D' 'H' 'D' 'D' 'H' 'A' 'D' 'D' 'H' 'H' 'A' 'D' 'H' 'H' 'H' 'A' 'D'
 'H' 'D' 'A' 'H' 'D' 'A' 'A' 'A' 'H' 'A' 'H' 'A' 'H' 'H' 'A' 'A' 'H' 'A'
 'A' 'H' 'D' 'A' 'H' 'H' 'H' 'A' 'A' 'H' 'D' 'D' 'H' 'H' 'D' 'A' 'H' 'A'
 'H' 'A' 'H' 'H' 'D' 'D' 'H' 'A' 'A' 'D' 'H' 'H' 'H' 'A' 'A' 'H' 'A' 'A'
 'A' 'H' 'H' 'A' 'H' 'A' 'D' 'A' 'A' 'H' 'A' 'A' 'D' 'H' 'D' 'A' 'H' 'H'
 'H' 'A' 'A' 'H' 'H' 'D' 'D' 'H' 'D' 'H' 'H' 'H' 'A' 'H' 'H' 'H' 'A' 'H'
 'A' 'H' 'D' 'A' 'H' 'H' 'A' 'A' 'D' 'D' 'H' 'H' 'A' 'D' 'H' 'D' 'H' 'H'
 'D' 'D' 'D' 'D' 'A' 'D' 'H' 'A' 'H' 'A' 'D' 'H' 'A' 'A' 'A' 'H' 'H' 'H'
 'H' 'A' 'A' 'A' 'D' 'A' 'D' 'D' 'A' 'H' 'H' 'A' 'D' 'A' 'H' 'A' 'A' 'D'
 'H' 'D' 'A' 'H' 'H' 'A' 'H' 'A' 'H' 'D' 'D' 'A' 'H' 'D' 'D' 'A' 'D' 'A'
 'H' 'H' 'H' 'D' 'A' 'A' 'A' 'H' 'A' 'D' 'A' 'A' 'H' 'D' 'A' 'A' 'H' 'H'
 'D' 'H' 'A' 'H' 'H' 'H' 'A' 'H' 'D' 'H' 'D' 'D' 'H

Encoding categorical dependent variable data

One - Hot encoding our dependent variable. Our dependent variable has 3 outcomes: Home win (H), Draw (D) and away win (A). We need to performe one-hot encoding on these categorical data in order to use them in the model as the dependent variable. After this encoding H win is encoded [0.0.1], Draw as [0.1.0] and Away win [1.0.0]. 

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# assuming your original dataframe is called 'y' and the column to be one-hot encoded is called 'outcome'
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='drop')

# reshape 'y' to a 2D numpy array with a single column
y_reshaped = y.reshape(-1, 1)

# transform the 'outcome' column to a numpy array and perform one-hot encoding using the ColumnTransformer
y_encoded = np.array(ct.fit_transform(y_reshaped))

In [10]:
print(y_encoded)

[[0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0.

### Splitting the dataset into the Training set and Test set

We will use the trainsplit function from the model selection module of sklearn. Test size is set at 0.2 meaning a 80% - 20% split. Random_state is set to 1. 

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[ 3.3   3.6   2.15 ...  3.39  3.69  2.1 ]
 [ 2.5   3.2   2.9  ...  2.52  3.16  3.01]
 [ 1.33  4.75 10.   ...  1.35  4.88  9.97]
 ...
 [ 5.5   4.    1.6  ...  5.47  4.13  1.61]
 [ 2.15  3.4   3.4  ...  2.19  3.38  3.42]
 [ 1.25  6.25 11.   ...  1.26  6.24 10.99]]


In [12]:
print(x_test)

[[ 1.16  8.   15.   ...  1.17  7.9  15.8 ]
 [ 3.25  3.1   2.38 ...  3.24  3.14  2.39]
 [ 1.45  4.75  7.   ...  1.45  4.77  7.01]
 ...
 [ 1.67  3.6   5.5  ...  1.69  3.73  5.32]
 [ 3.2   3.5   2.2  ...  3.19  3.63  2.19]
 [ 2.45  3.25  2.9  ...  2.54  3.18  2.96]]


In [13]:
print(y_train)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1.

In [14]:
print(y_test)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


### Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [16]:
print(x_train)

[[ 0.24915103 -0.35508903 -0.66438119 ...  0.28915899 -0.28567948
  -0.68233088]
 [-0.23253724 -0.83438433 -0.3924378  ... -0.2312275  -0.90054292
  -0.3610417 ]
 [-0.93700634  1.02288495  2.18195956 ... -0.93105763  1.09486297
   2.09629099]
 ...
 [ 1.57379377  0.12420627 -0.86380634 ...  1.53330143  0.22477319
  -0.85533275]
 [-0.44327586 -0.59473668 -0.21114222 ... -0.42861549 -0.64531658
  -0.21628503]
 [-0.98517517  2.82024232  2.54455074 ... -0.98489071  2.67262576
   2.45641733]]


In [17]:
print(x_test)

[[-1.0393651   4.91715925  3.99491546 ... -1.0387238   4.59842447
   4.15466018]
 [ 0.21904551 -0.95420815 -0.58098522 ...  0.19943718 -0.92374531
  -0.57994202]
 [-0.8647531   1.02288495  1.09418603 ... -0.87124309  0.9672498
   1.05121847]
 ...
 [-0.73228882 -0.35508903  0.55029926 ... -0.72768819 -0.23927469
   0.45453855]
 [ 0.18893999 -0.47491285 -0.64625163 ...  0.16952991 -0.35528666
  -0.65055503]
 [-0.26264276 -0.77447241 -0.3924378  ... -0.2192646  -0.87734052
  -0.37869495]]


## Part 2 - Building the ANN

### Initializing the ANN

In [18]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation = "relu"))

### Adding the second hidden layer

In [20]:
ann.add(tf.keras.layers.Dense(units=6, activation = "relu"))

### Adding the output layer

Here we are adding the output layer and since our dependent variable is the outcome of the game represented as three independent classes (H, D and A) that are one hot encoded we need the "units" parameter to be set to three because we need three neurons to produce a binary outcome that encodes each class. The "activation" parameter of the output layer also needs to be set to a sigmoid activation function. That is because a sigmoid function produces the predictions as well as the probabilities of each outcome.

In [21]:
ann.add(tf.keras.layers.Dense(units=3, activation = "softmax"))

## Part 3 - Training the ANN

### Compiling the ANN

In [24]:
ann.compile(optimizer= "adam", loss= "categorical_crossentropy", metrics= ["accuracy"])

### Training the ANN on the Training set

In [26]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 10000)

Streaming output truncated to the last 5000 lines.
7/7 [==============================] - 0s 4ms/step - loss: 0.3658 - accuracy: 0.8333
Epoch 7502/10000
7/7 [==============================] - 0s 4ms/step - loss: 0.3711 - accuracy: 0.8241
Epoch 7503/10000
7/7 [==============================] - 0s 4ms/step - loss: 0.3724 - accuracy: 0.8241
Epoch 7504/10000
7/7 [==============================] - 0s 4ms/step - loss: 0.3663 - accuracy: 0.8287
Epoch 7505/10000
7/7 [==============================] - 0s 3ms/step - loss: 0.3749 - accuracy: 0.8194
Epoch 7506/10000
7/7 [==============================] - 0s 4ms/step - loss: 0.3727 - accuracy: 0.8472
Epoch 7507/10000
7/7 [==============================] - 0s 4ms/step - loss: 0.3819 - accuracy: 0.8194
Epoch 7508/10000
7/7 [==============================] - 0s 4ms/step - loss: 0.3768 - accuracy: 0.8241
Epoch 7509/10000
7/7 [==============================] - 0s 4ms/step - loss: 0.3798 - accuracy: 0.8194
Epoch 7510/10000
7/7 [==========================

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Solution**

In [ ]:
ann.predict([[]])

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
y_pred = y_pred.astype(int)
print(y_pred)

2/2 [==============================] - 0s 2ms/step
[[0 0 1]
 [0 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]]


In [ ]:
# Define the mapping of class indices to labels
label_map = {0: "A", 1: "D", 2: "H"}

# Transform the matrix y_pred to a matrix of labels
y_pred_labels = np.argmax(y_pred, axis=1)
y_pred_labels = [label_map[i] for i in y_pred_labels]

print(y_pred_labels)

['H', 'A', 'H', 'A', 'H', 'H', 'H', 'H', 'H', 'D', 'A', 'H', 'A', 'A', 'H', 'D', 'A', 'A', 'H', 'A', 'H', 'H', 'A', 'H', 'H', 'H', 'A', 'H', 'D', 'A', 'H', 'A', 'A', 'H', 'H', 'D', 'A', 'H', 'A', 'D', 'A', 'D', 'H', 'A', 'D', 'D', 'A', 'D', 'D', 'H', 'A', 'H', 'A', 'H']


### Making the Confusion Matrix